---
name: "tox"

on:
  - pull_request
  - push

jobs:

  pytest:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
          - tox-env: py36
            py-ver: 3.6
          - tox-env: py38
            py-ver: 3.8

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.py-ver }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py-ver }}

      - name: Install dependencies
        run: |
          sudo apt install libvirt-dev -y
          python --version
          python -m pip install --upgrade pip
          pip install tox
          pip install ".[dev]"

      - name: Test with tox
        env:
          TOXENV: ${{ matrix.tox-env }}
        run: tox

  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt install libvirt-dev -y
          python -m pip install --upgrade pip
          pip install tox
          pip install ".[dev]"

      - name: Run lint with tox
        env:
          TOXENV: lint
        run: tox
