---
name: "tox"

on:
  - pull_request
  - push

jobs:

  pytest:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
          - py-ver: 3.6
          - py-ver: 3.8

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.py-ver }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py-ver }}

      - name: Install dependencies
        run: |
          sudo apt install libvirt-dev -y
          python -m pip install --upgrade pip
          pip install "tox>=3.24,<4"
          pip install ".[dev]"
          pip install .
          pip list

      - name: Test with tox
        run: |
          tox --version
          tox
